### ISSUE TITLE
Handler file names don't work in Windows

### ISSUE THREAD

**Issue by spcfran** [adriaan-pelzer/deconstruct-api#1]
Windows doesn't allow `:` in file names, so when trying to clone a repo with routes it spits out a lot of errors e.g:
`error: unable to create file src/routes/~:type~:iid~:childType~get.js: Invalid argument`

It might be a good idea to replace that with a [valid character](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) in a similar way that `/`s are replaced with `~`s.

**Comment by adriaan-pelzer** [comment]
Cool - I agree. Never tested on Windows!

Here's how I think it could/should be done:
Currently the "loadRoutes" function takes one argument, namely "routeDir". This should keep working for backwards compatibility. Let's however, change this to "options" or "params" or something, and if it is a string, assume it is the routeDir spec. If, however, it is an object, get two parameters from it, namely routeDir and pathParameterFlag (or something more suitable). The latter defaults to colon, but can be changed to anything else.
